# Generated by Django 4.1.1 on 2022-09-28 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortalplanet', '0002_category_location_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='poster',
        ),
    ]
