# Generated by Django 4.1.1 on 2022-09-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortalplanet', '0003_rename_user_post_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PostImages/'),
        ),
    ]
