# Generated by Django 4.1.1 on 2022-10-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortalplanet', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='share',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PostImages'),
        ),
    ]
