# Generated by Django 4.1.1 on 2022-10-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortalplanet', '0006_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='active',
            new_name='open',
        ),
    ]
