# Generated by Django 4.1.1 on 2022-11-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortalplanet', '0007_rename_active_post_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='body',
        ),
    ]
