# Generated by Django 4.1.1 on 2022-11-03 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortalplanet', '0008_rename_message_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='messages_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
